sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t pavel0793/docker-react-f Dockerfile.dev .

script:
  - docker run -e CI=true pavel0793/docker-react npm run test
