language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t pavel0793/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pavel0793/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-663845222256"
  bucket_path: "docker-react"
  on:
    branch: master
  acess_key_id: "$AWS_ACESS_KEY"
  secret_access_key: :
    secure: "$AWS_SECRET_KEY"